#!/bin/sh

# General
alias \
  cf="cd /home/snooze/.config && ls -a" \
  sc="cd /home/snooze/.local/bin && ls -a" \
  src="cd /home/snooze/.local/src/ && ls -a" \
  cfdwm="cd ~/.local/src/dwm/ && ls -a" \
  cfdwmb="cd ~/.local/src/dwmblocks/ && ls -a" \
  cfst="cd ~/.local/src/st/ && ls -a" \
  cfa="$EDITOR ~/.config/shell/aliasrc" \
  cfv="cd ~/.config/nvim/" \
  cfz="$EDITOR ~/.config/zsh/.zshrc" \
  cfb="$EDITOR $HOME/.local/share/bookmark" \
  z="zathura" \
  smci="sudo make clean install" \
  config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" \
  cs="xclip -selection clipboard" \
  sdn="sudo shutdown -h now" \
  kvb="sudo killall -9 viber" \
  lf="lfrun" \
  pip='python -m pip' \
  upd='paru -Syu' \
  ..='cd ../' \
  ...='cd ../..' \
  ....='cd ../../..' \
  .....='cd ../../../..' \
  ......='cd ../../../../..' \
  venv='source venv/bin/activate' \
  yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config \
  dcup='docker-compose up' \
  dcb='docker-compose build' \
  dcupb='docker-compose up --build' \
  dcrm='docker-compose rm' \
  dcps='docker-compose ps' \
  dcstop='docker-compose stop' \
  dcrestart='docker-compose restart' \
  access='wine /home/snooze/.wine/drive_c/Program\ Files\ (x86)/Microsoft\ Office/Office12/MSACCESS.EXE'

# Functions
function dc() {
  if [ -e "docker-compose/${1}" ]; then
      docker-compose -f docker-compose.yml -f docker-compose/"${1}" "${@:2:101}"
  else
      docker-compose "${@:1:101}"
  fi
}
  # pomo='sleep 3000 && dunst | notify-send "break"' \

# List directory contents
alias ll='ls -lh'
alias la='ls -lah'

# Verbosity settings
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	md="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best"

# Colorize commands when possible.
alias \
	ls="exa -h --icons -a --group-directories-first" \
	grep="rg --color=auto" \
	diff="diff --color=auto" \
	cat="bat --color=always --style=full" \
	ip="ip -color=auto"

# Git
alias \
  ga='git add' \
  gcmsg='git commit -m' \
  gs='git status' \
  gpull='git pull' \
  gp='git push' \
  gd='git diff' \
  lg='lazygit' \
  sync-notes='zk save sync; git add ~/org && git commit -m "sync" && git push'

# Django
alias \
  mpy='python manage.py' \
  runserver='python manage.py runserver' \
  testserver='python manage.py testserver'
