#!/bin/sh
alias cf="cd /home/snooze/.config && ls -a" \
sc="cd /home/snooze/.local/bin && ls -a" \
src="cd /home/snooze/.local/src/ && ls -a" \
cfdwm="sudo $EDITOR ~/.local/src/dwm/config.h" \
cfdwmb="sudo $EDITOR ~/.local/src/dwmblocks/blocks.h" \
cfst="sudo $EDITOR ~/.local/src/st/config.h" \
cfa="$EDITOR ~/.config/shell/aliasrc" \
cfv="cd ~/.config/nvim/" \
cfz="$EDITOR ~/.config/zsh/.zshrc" \
z="zathura" \
smci="sudo make clean install" \
config="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" \
cs="xclip -selection clipboard" \
sdn="sudo shutdown -h now" \
kvb="sudo killall -9 viber" \
lf="lfrun" \
pomo='sleep 3000 && dunst | notify-send "break"' \
