#!/bin/zsh

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH=/home/snooze/.cargo/bin:$PATH
export PATH=/home/snooze/.config/emacs/bin:$PATH
export PATH=/home/snooze/.local/share/gem/ruby/3.0.0/bin:$PATH

export TERMINAL="st"
export BROWSER="chromium"
export EDITOR="nvim"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority # I don't use a DM, but it may break if you use one
export OPAMROOT="$XDG_DATA_HOME/opam"
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export SOLARGRAPH_CACHE="$XDG_CACHE_HOME/solargraph"

# Other program settings
export AWT_TOOLKIT="MToolkit wmname LG3D"	# May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm

# for nvim lsp
export JDTLS_HOME="$HOME/.local/share/nvim/lsp_servers/jdtls/" # for java

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
