#!/bin/zsh

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH=/home/snooze/.cargo/bin:$PATH
export PATH=/home/snooze/.config/emacs/bin:$PATH
export PATH=/home/snooze/.local/share/gem/ruby/3.0.0/bin:$PATH
export PATH=/home/snooze/.local/share/npm/bin:$PATH

export TERMINAL="st"
export BROWSER="firefox"
export EDITOR="nvim"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority # I don't use a DM, but it may break if you use one
export OPAMROOT="$XDG_DATA_HOME/opam"
export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export SOLARGRAPH_CACHE="$XDG_CACHE_HOME/solargraph"
export ZK_NOTEBOOK_DIR="$HOME/notes"
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export REDISCLI_HISTFILE="$XDG_DATA_HOME"/redis/rediscli_history
export PSQL_HISTORY="$XDG_DATA_HOME/psql_history"
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export AWT_TOOLKIT="MToolkit wmname LG3D"	# May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm
export ANDROID_HOME="$XDG_DATA_HOME"/android
export DJANGO_SETTINGS_MODULE=config.settings
export GOPATH="$XDG_DATA_HOME"/go
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH=/home/snooze/.cargo/bin:$PATH
export PATH=/home/snooze/.emacs.d/bin:$PATH
export PATH=$JAVA_HOME/bin:$PATH
export PATH=/home/snooze/.local/share/gem/ruby/3.0.0/bin:$PATH
export PATH=/home/snooze/.local/share/smlformat/:$PATH

# lf icons
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"

[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
