---
root-markers:
  - .git/

tools:
  yamllint: &yamllint
    lint-command: "yamllint -f parsable -"
    lint-stdin: true

  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy --strict --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  clang-tidy: &clang-tidy
    lint-command: "clang-tidy"

languages:
  python:
    - <<: *python-flake8
    - <<: *python-mypy
  yaml:
    - <<: *yamllint
  c:
    - <<: *clang-tidy
