#!bin/sh

xrandr --dpi 96
xset r rate 300 60 &
xset -dpms
xset s off
sudo ntpd -qg
autostart="mpd unclutter pipewire remaps"
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
# initialize environments automatically
eval $(opam env)
eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
xbanish &

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
feh --bg-scale ~/.config/wallpaper.jpg
. /home/snooze/.nix-profile/etc/profile.d/nix.sh
